### ISSUE TITLE
Crash during text selection in GUI apps when fcitx5 is installed

### ISSUE THREAD

**Issue by artyommironov** [WayfireWM/wayfire#1471]
WM crashes during text selection in some GUI apps when fcitx5 is installed.
Tested apps: qutebrowser, chromium, FeatherPad, IntelliJ IDEA, Android Studio.

**Steps to reproduce**
1. Install and run fcitx5 (can use `input = fcitx5` in `[autorun]` wayfire config section)
2. Open an app where you can select preferably long texts, for example I opened [this link](https://raw.githubusercontent.com/DrKLO/Telegram/master/TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java) in qutebrowser
3. Start selecting text by click-and-hold mouse button at the text and moving cursor down
4. After some time during text selection WM will crash

Length of selected text seems doesn't matter, because just a usual editing session in the IDEA will crash randomly after few minutes.

**Expected behavior**
Not crashing. Sway WM is not crashing in this case.

**Screenshots or stacktrace**
```
II 07-05-22 15:25:12.841 - [src/main.cpp:288] Starting wayfire version 0.8.0-94f15048 (May  7 2022, branch 'HEAD')
II 07-05-22 15:25:12.841 - [libseat] [libseat/libseat.c:73] Seat opened with backend 'seatd'
II 07-05-22 15:25:12.841 - [libseat] [libseat/backend/seatd.c:228] Enabling seat
II 07-05-22 15:25:12.841 - [backend/session/session.c:110] Successfully loaded libseat session
II 07-05-22 15:25:12.842 - [backend/backend.c:220] Found 1 GPUs
II 07-05-22 15:25:12.842 - [backend/drm/backend.c:183] Initializing DRM backend for /dev/dri/card0 (i915)
II 07-05-22 15:25:12.842 - [backend/drm/drm.c:251] Found 3 DRM CRTCs
II 07-05-22 15:25:12.842 - [backend/drm/drm.c:178] Found 9 DRM planes
II 07-05-22 15:25:12.843 - [render/egl.c:180] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
II 07-05-22 15:25:12.877 - [render/egl.c:326] Using EGL 1.5
II 07-05-22 15:25:12.877 - [render/egl.c:327] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display 
II 07-05-22 15:25:12.877 - [render/egl.c:329] Supported EGL device extensions: EGL_EXT_device_drm EGL_EXT_device_drm_render_node
II 07-05-22 15:25:12.877 - [render/egl.c:331] EGL vendor: Mesa Project
II 07-05-22 15:25:12.880 - [render/gles2/renderer.c:737] Creating GLES2 renderer
II 07-05-22 15:25:12.880 - [render/gles2/renderer.c:738] Using OpenGL ES 3.2 Mesa 21.3.7
II 07-05-22 15:25:12.880 - [render/gles2/renderer.c:739] GL vendor: Intel
II 07-05-22 15:25:12.880 - [render/gles2/renderer.c:740] GL renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
II 07-05-22 15:25:12.880 - [render/gles2/renderer.c:741] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_INTEL_conservative_rasterization GL_INTEL_performance_query GL_ANDROID_extension_pack_es31a GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_NV_fragment_shader_interlock GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clear_texture GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_texture_compression_bptc GL_EXT_texture_mirror_clamp_to_edge GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_EXT_texture_query_lod GL_MESA_bgra 
II 07-05-22 15:25:12.888 - [src/default-config-backend.cpp:97] Using config file: /home/user/.config/wayfire.ini
II 07-05-22 15:25:12.888 - [subprojects/wf-config/src/file.cpp:576] Reading XML configuration options from directory /opt/wayfire/share/wayfire/metadata
II 07-05-22 15:25:12.889 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/scale-title-filter.xml
II 07-05-22 15:25:12.889 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/fast-switcher.xml
II 07-05-22 15:25:12.889 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/input-device.xml
II 07-05-22 15:25:12.889 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/vswitch.xml
II 07-05-22 15:25:12.890 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/command.xml
II 07-05-22 15:25:12.890 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/simple-tile.xml
II 07-05-22 15:25:12.891 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/extra-gestures.xml
II 07-05-22 15:25:12.891 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/invert.xml
II 07-05-22 15:25:12.891 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/preserve-output.xml
II 07-05-22 15:25:12.891 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/idle.xml
II 07-05-22 15:25:12.891 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/core.xml
II 07-05-22 15:25:12.891 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/vswipe.xml
II 07-05-22 15:25:12.891 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/blur.xml
II 07-05-22 15:25:12.892 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/output.xml
II 07-05-22 15:25:12.892 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wobbly.xml
II 07-05-22 15:25:12.892 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/animate.xml
II 07-05-22 15:25:12.892 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/place.xml
II 07-05-22 15:25:12.892 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/autostart.xml
II 07-05-22 15:25:12.892 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/move.xml
II 07-05-22 15:25:12.893 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/expo.xml
II 07-05-22 15:25:12.893 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/window-rules.xml
II 07-05-22 15:25:12.893 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wrot.xml
II 07-05-22 15:25:12.893 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wm-actions.xml
II 07-05-22 15:25:12.893 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/cube.xml
II 07-05-22 15:25:12.893 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/alpha.xml
II 07-05-22 15:25:12.894 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/workarounds.xml
II 07-05-22 15:25:12.894 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/grid.xml
II 07-05-22 15:25:12.894 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/switcher.xml
II 07-05-22 15:25:12.894 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/zoom.xml
II 07-05-22 15:25:12.894 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/oswitch.xml
II 07-05-22 15:25:12.894 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/fisheye.xml
II 07-05-22 15:25:12.895 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/resize.xml
II 07-05-22 15:25:12.895 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/input.xml
II 07-05-22 15:25:12.895 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/scale.xml
II 07-05-22 15:25:12.895 - [subprojects/wf-config/src/file.cpp:589] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/decoration.xml
II 07-05-22 15:25:12.899 - [backend/headless/backend.c:82] Creating headless backend
II 07-05-22 15:25:12.899 - [backend/headless/backend.c:18] Starting headless backend
II 07-05-22 15:25:12.901 - [xwayland/server.c:92] Starting Xwayland on :0
II 07-05-22 15:25:12.901 - [src/main.cpp:348] Using socket name wayland-1
II 07-05-22 15:25:12.988 - [src/core/seat/input-manager.cpp:46] handle new input: Power Button, default mapping: (null)
II 07-05-22 15:25:13.003 - [src/core/seat/input-manager.cpp:46] handle new input: Video Bus, default mapping: (null)
II 07-05-22 15:25:13.017 - [src/core/seat/input-manager.cpp:46] handle new input: Power Button, default mapping: (null)
II 07-05-22 15:25:13.025 - [src/core/seat/input-manager.cpp:46] handle new input: Sleep Button, default mapping: (null)
II 07-05-22 15:25:13.031 - [src/core/seat/input-manager.cpp:46] handle new input: Logitech B330/M330/M331, default mapping: (null)
II 07-05-22 15:25:13.036 - [src/core/seat/input-manager.cpp:46] handle new input: Logitech B330/M330/M331, default mapping: (null)
II 07-05-22 15:25:13.036 - [src/core/seat/input-manager.cpp:46] handle new input: my keyboard, default mapping: (null)
II 07-05-22 15:25:13.041 - [src/core/seat/input-manager.cpp:46] handle new input: my keyboard Mouse, default mapping: (null)
II 07-05-22 15:25:13.041 - [src/core/seat/input-manager.cpp:46] handle new input: my keyboard System Control, default mapping: (null)
II 07-05-22 15:25:13.044 - [src/core/seat/input-manager.cpp:46] handle new input: my keyboard Consumer Control, default mapping: (null)
II 07-05-22 15:25:13.048 - [src/core/seat/input-manager.cpp:46] handle new input: my keyboard Consumer Control, default mapping: (null)
II 07-05-22 15:25:13.048 - [backend/drm/drm.c:1185] Scanning DRM connectors on /dev/dri/card0
II 07-05-22 15:25:13.052 - [backend/drm/drm.c:1251] Found connector 'DP-1'
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1251] Found connector 'DP-2'
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1287] 'DP-2' connected
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1298] Physical size: 510x290
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1338] Detected modes:
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   1920x1080@60000 (preferred)
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   1600x900@60000 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   1280x1024@75025 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   1280x1024@60020 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   1152x864@75000 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   1024x768@75029 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   1024x768@60004 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   800x600@75000 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   800x600@60317 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   640x480@75000 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   640x480@59940 
II 07-05-22 15:25:13.057 - [backend/drm/drm.c:1360]   720x400@70082 
II 07-05-22 15:25:13.061 - [backend/drm/drm.c:1251] Found connector 'HDMI-A-1'
II 07-05-22 15:25:13.061 - [backend/drm/drm.c:1412] connector DP-2: Requesting modeset
II 07-05-22 15:25:13.061 - [src/core/output-layout.cpp:1096] new output: DP-2 ("***")
II 07-05-22 15:25:13.061 - [src/core/output-layout.cpp:430] loaded mode auto
II 07-05-22 15:25:13.065 - [backend/drm/drm.c:708] connector DP-2: Modesetting with '1920x1080@60000mHz'
(type equals variant: [type: string, value: toplevel] | (type equals variant: [type: string, value: x-or] & focusable equals variant: [type: bool, value: 1]))
type equals variant: [type: string, value: overlay]
false
false
false
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "Power Button" to output (not found in this cursor)
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "Video Bus" to output (not found in this cursor)
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "Power Button" to output (not found in this cursor)
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "Sleep Button" to output (not found in this cursor)
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "Logitech B330/M330/M331" to output (not found in this cursor)
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "my keyboard" to output (not found in this cursor)
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "my keyboard System Control" to output (not found in this cursor)
EE 07-05-22 15:25:13.111 - [types/wlr_cursor.c:856] Cannot map device "my keyboard Consumer Control" to output (not found in this cursor)
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
EE 07-05-22 15:25:13.203 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:13.205 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:13.231 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
II 07-05-22 15:25:13.233 - [src/core/seat/input-manager.cpp:46] handle new input: virtual keyboard, default mapping: (null)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "Power Button" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "Video Bus" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "Power Button" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "Sleep Button" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "Logitech B330/M330/M331" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "my keyboard" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "my keyboard System Control" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "my keyboard Consumer Control" to output (not found in this cursor)
EE 07-05-22 15:25:13.237 - [types/wlr_cursor.c:856] Cannot map device "virtual keyboard" to output (not found in this cursor)
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
EE 07-05-22 15:25:13.319 - [src/view/xwayland.cpp:815] new unmanaged xwayland surface (null) class: (null) instance: (null)
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
II 07-05-22 15:25:15.272 - [src/view/xdg-shell.cpp:201] new xdg_shell_stable surface: (null) app-id: (null)
EE 07-05-22 15:25:16.317 - [src/view/view-impl.cpp:62] Setting minimize hint to unknown surface. Wayfire currentlysupports only setting hints relative to views.
EE 07-05-22 15:25:55.989 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:56.546 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:56.604 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:56.611 - [src/view/xwayland.cpp:815] new unmanaged xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:56.616 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:56.968 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:56.981 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:58.885 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

.. skipped multiple same BUG lines ..

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

EE 07-05-22 15:25:59.200 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:59.201 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:59.201 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:59.208 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:59.208 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:59.208 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
EE 07-05-22 15:25:59.208 - [xwayland/xwm.c:1564] xcb error: op 2:0, code 3, sequence 302, value 6291538
EE 07-05-22 15:26:10.126 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)

.. skipped hundreds of same line

EE 07-05-22 15:26:21.161 - [src/view/xwayland.cpp:532] new xwayland surface (null) class: (null) instance: (null)
(EE) failed to read Wayland events: Broken pipe
```

**Wayfire version**
0.7.2, 0.8.0-94f15048 (installed using wf-install)

I tried to add debugging options but resulting binary was not able to run GUI apps, seems because of some issue with XWayland.

**Comment by howIsPassword** [comment]
I met the same problem. when I select text in  IntelliJ IDEA,  the wayfire crash

**Comment by aowon** [comment]
I also have the same problem, when I use CLion.

**Comment by LeoGitHuber** [comment]
I met the same problem too.

**Comment by liudng** [comment]
This only happens when text is selected in the Xwayland app. There are some FICTX plugins that use selection or clipboard. Try disabling these Fcitx plugins.

**Comment by killown** [comment]
I started fcitx from cmd, started clion, selected a text of more than 1000 lines and seems ok, no crashes, maybe fixed at some point?

**Comment by ammen99** [comment]
I also failed to reproduce this issue. Can someone still reproduce the problem with latest wayfire+wlroots? Is there a backtrace at the end of the log / wayfire's stdout?
