### ISSUE TITLE
wayfire-0.7.3 breaks screen sharing with firefox

### ISSUE THREAD

**Issue by m1027** [WayfireWM/wayfire#1526]
Hi,

with wayfire-0.7.2 I was able to share my (entire) screen in firefox like this under Gentoo/systemd:

- reboot into pure greetd/wayfire based wayland session
- /usr/libexec/xdg-desktop-portal-wlr # keep console open
- /usr/libexec/xdg-desktop-portal -r # keep another console open
- firefox meet.jit.si # start arbitrary video conference and share desktop

With wayfire-0.7.3 firefox just does nothing.

FYI: I can toggle between wayfire-0.7.2 and 0.7.3 and always reproduce that currently.

Let me know if I should do any further tests.

**Comment by m1027** [comment]
Fixed by upgrade from wlroots-0.15.0 to 0.15.1.

**Comment by stellarpower** [comment]
Wayfire has just come into the Ubuntu repos (for Lunar) at 0.7.4 and I have wlroots at 0.15.1 - screen sharing still not functional for me. Is there anything else I need to do or may be missing?

**Comment by stellarpower** [comment]
Okay, seems the package providing `/usr/libexec/xdg-desktop-portal-wlr` was missing - this is critical, and as it was in the autostart entries in my config, I didn't see any errors output. This package was not installed automatically for me when I installed wayfire itself, for anyone experiencing the same.
