### ISSUE TITLE
Focus remains grabbed when opening a menu and view is changed

### ISSUE THREAD

**Issue by stefonarch** [WayfireWM/wayfire#1754]
**Describe the bug**

It concerns only applications with textedit (`featherpad`, `libreoffice --writer`), opening a context menu or the applications menu of `lxqt-panel' without doing an action grabs focus when changing view.

**To Reproduce**
1.  Open 2 windows with texxedit, start typing in one
2.  Right click to open the context menu
3. Switch to the other window, the menu  in the first window will be closed
4. Continue typing, focus is still in the first window, clicking won't help. 
5. Workspace switch or clicking in the first window again will release the focus.

**Expected behavior**

Focus will not be grabbed after opening (and leaving open) context menus.

**Wayfire version**
 0.8.0-4dd373d2 (Mar  3 2023, branch 'master')

**Comment by marcusbritanicus** [comment]
I can confirm this bug. I hit upon this bug with terminal (foot/desq-term) and lxqt-panel.

**Comment by tsujan** [comment]
Just wanted to add that the bug doesn't exist in the stable Wayfire 0.7.5. But I confirm that it exists in git.

**Comment by ammen99** [comment]
I think some issues like that may have been just fixed in master, can any one of you confirm?

**Comment by stefonarch** [comment]
It is not fixed, recompiled yesterday.  It's the biggest issue with lxqt-shell-plugin.
