### ISSUE TITLE
Build failure on Arch from AUR.

### ISSUE THREAD

**Issue by mothsarecool524** [WayfireWM/wayfire#2359]
**Describe the bug**

**To Reproduce**
1. Install `wayfire` and `wcm` from AUR via `yay`.
2. Build fail occurs on `wayfire`, `wf-config`, `wf-shell-git`, and `wf-shell`, `wf-config` with `exit status 4`, and the rest with `exit status 8`.

**Expected behavior**
I expected it to resolve some dependencies, but those dependencies failed to build.

**Screenshots or stacktrace**
![image](https://github.com/WayfireWM/wayfire/assets/124483129/c9e0347d-21e4-4fa8-a224-63c91fb5c260)
This error repeats itself multiple times throughout the output of the command, for each package listed above.
If you want, I can post a pastebin link with the full output of the command that I used to try and install Wayfire and wcm.

**Wayfire version**
Latest AUR version at the time of writing, which is 0.8.1-4

**Comment by ammen99** [comment]
This was fixed in #2352.

**Comment by kode54** [comment]
#2352 probably doesn't fix the stable tags used by the non-git packages.
