### ISSUE TITLE
Prevent Waybar from hiding.

### ISSUE THREAD

**Issue by AgostinoA** [WayfireWM/wayfire#2585]
**Describe the bug**  
I've been going crazy for days and can't figure out how this issue started. I updated both Wayfire to the latest version and Waybar, and from that moment on, this problem appeared: when I open a fullscreen app, especially with Wine, Waybar leaves an empty space in the bar area and doesn't go fully fullscreen.  

I'm not sure if it's an IPC request timing issue or something else. However, if I toggle fullscreen on and off from within the game, it works correctly.  

Additionally, in some games like *Crysis 2*, all mouse position events become misaligned, making the cursor behave erratically.  

**To Reproduce**  
1. Open a game in fullscreen.  

**Expected behavior**  
I expect that any app running in fullscreen should cover the entire screen and that mouse input should remain accurate.  

**Screenshots or stacktrace**  

![Image](https://github.com/user-attachments/assets/3cb854b1-7dd8-4a55-9327-c147ed2b5c8f)  

![Image](https://github.com/user-attachments/assets/ccac0584-cbca-415c-a4b9-2375eb74c4ee)

**Wayfire version**  
git

**Comment by soreau** [comment]
It might be 78899608 causing the problem. Does the commit before this one work ok?

**Comment by AgostinoA** [comment]
it didn't do it before

**Comment by AgostinoA** [comment]
I found a report from another user experiencing the same issue on Waybar:  
[[Waybar Issue #3387](https://github.com/Alexays/Waybar/issues/3387)](https://github.com/Alexays/Waybar/issues/3387).  
Now, I'm not sure if the issue is caused by Wayfire or Waybar. 😅

**Comment by soreau** [comment]
Maybe check if `wf-panel` does the same thing.

**Comment by CarloWood** [comment]
"Waybar leaves an empty space in the bar area and doesn't go fully fullscreen."
You want waybar to go full screen?

**Comment by AgostinoA** [comment]
I want the empty space not to remain

**Comment by AgostinoA** [comment]
> Maybe check if `wf-panel` does the same thing.

Same problem, even with wf-panel. I created a simple fullscreen screen using GLFW.  
Check if it happens to you as well, because I can't figure out if it's only on my configurations or something else.  
I'm uploading a compiled executable for testing.  

![Image](https://github.com/user-attachments/assets/d5357580-6ea5-4775-88af-0b0ab91727c3)  

I'm also uploading the code for a test.

```c++
#include <GLFW/glfw3.h>

int main() {
    if (!glfwInit()) return -1;

    GLFWmonitor* primaryMonitor = glfwGetPrimaryMonitor();
    const GLFWvidmode* mode = glfwGetVideoMode(primaryMonitor);

    glfwWindowHint(GLFW_RED_BITS, mode->redBits);
    glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
    glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
    glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);

    GLFWwindow* window = glfwCreateWindow(mode->width, mode->height, "Fullscreen Red", primaryMonitor, nullptr);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);

    while (!glfwWindowShouldClose(window)) {
        glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        
        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```

**Comment by AgostinoA** [comment]
@soreau but do you have this problem?

**Comment by ammen99** [comment]
@AgostinoA thanks for your glfw example, I can reproduce the issue. Will look into it and let you know when a bug fix is available.

**Comment by AgostinoA** [comment]
@ammen99 Go figure, it's a real pleasure for me. I'm here to find as many bugs as possible and give support to the project.

**Comment by AgostinoA** [comment]
Have you tried with a bar like wf-panel or waybar? Because the problem is still evident to me.

**Comment by killown** [comment]
> Have you tried with a bar like wf-panel or waybar? Because the problem is still evident to me.

https://github.com/user-attachments/assets/4ded8b24-f8a9-4128-8f9a-40098778ef0f

**Comment by killown** [comment]
> Kindly can you share your wayfire.ini configuration? Did you compile using the master branch version or from your commit ?

If you share your config, I can check whether the issue is in the configuration or not.

**Comment by AgostinoA** [comment]
Sorry for the trouble, but I still haven’t figured out this issue.
I’m sharing my test base Wayfire and Waybar configs, I’m going crazy over this 😅
I don’t understand how you managed to get it working without making any specific code changes.

[waybar.ini.txt](https://github.com/user-attachments/files/21327479/waybar.ini.txt)
[wayfire.ini.txt](https://github.com/user-attachments/files/21327480/wayfire.ini.txt)

**Comment by ammen99** [comment]
I can reproduce this bug in normal usage quite often, though not every time. It is a very weird bug but I'll be looking into it more, this is why I added it to the 0.10 milestone.

**Comment by ammen99** [comment]
> However maybe I understood the problem from where it could arise from the reflow reserved areas method (workarea), it is missing the concept that if a window is in pending fullscreen it must exclude anchors

The method is simply computing the workarea. But the workarea is a 'hint', fullscreen windows simply ignore it and take the full space.

**Comment by AgostinoA** [comment]
I closed by mistake, sorry

**Comment by killown** [comment]
it's something from the config, not happening here, if you paste your config or at least give the plugins list, I could compare.

**Comment by ammen99** [comment]
@killown It is also worth mentioning it does not happen every time for me. Sometimes it works, sometimes it does not.

**Comment by AgostinoA** [comment]
Fullscreen must try on X11-based apps, as an example I passed along (GLFW)

**Comment by AgostinoA** [comment]
[glfw_main_x11.zip](https://github.com/user-attachments/files/21345675/glfw_main_x11.zip)

try this

**Comment by AgostinoA** [comment]
It’s possible that the fullscreen event is emitted at the time the window is created (via wlr-foreign-toplevel-management-unstable protocol), but at that moment the window is not yet actually in fullscreen. As a result, Wayfire adds the anchors without recognizing the fullscreen state.

For example, Waybar behaves correctly: as soon as it detects a fullscreen app, it quickly hides itself. So, summing up, the issue seems to be related to how fullscreen events are handled likely a timing or event ordering problem ?

**Comment by AgostinoA** [comment]
I tried GLFW with the Wayland protocol and the problem does not occur.

**Comment by AgostinoA** [comment]
@killown Try glfw x11 i passed you let me know, i repeat sorry for the trouble. Tell me at your place what happens, if it works at your place XD

**Comment by killown** [comment]
> It’s possible that the fullscreen event is emitted at the time the window is created (via wlr-foreign-toplevel-management-unstable protocol), but at that moment the window is not yet actually in fullscreen. As a result, Wayfire adds the anchors without recognizing the fullscreen state.
> 
> For example, Waybar behaves correctly: as soon as it detects a fullscreen app, it quickly hides itself. So, summing up, the issue seems to be related to how fullscreen events are handled likely a timing or event ordering problem ?

For me, you're not exiting fullscreen somehow. Wayfire detects the exit event, but the view remains fullscreen. The reserved layer shell area stays active then give you the empty space while waybar stays hidden.

I am saying that because toggle fullscreen wasn't working in ammen config with your glfw x11, I had to move the view to resize it then toggle to fullscreen again.

**Comment by killown** [comment]
The issue is happening here when explicitly requests fullscreen after creation:

```
#include <GL/gl.h>
#include <SDL.h>

int main() {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Window *window =
      SDL_CreateWindow("SDL Fullscreen", SDL_WINDOWPOS_CENTERED,
                       SDL_WINDOWPOS_CENTERED, 800, 600, SDL_WINDOW_OPENGL);

  if (!window) {
    SDL_Log("Failed to create window: %s", SDL_GetError());
    return -1;
  }

  SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);

  SDL_GLContext context = SDL_GL_CreateContext(window);

  bool running = true;
  while (running) {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
      if (ev.type == SDL_QUIT)
        running = false;
    }

    glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    SDL_GL_SwapWindow(window);
  }

  SDL_GL_DeleteContext(context);
  SDL_DestroyWindow(window);
  SDL_Quit();
  return 0;
}

```
 g++ try-this -I/usr/include/SDL2 -lSDL2 -lGL

SDL_VIDEODRIVER=x11 ./a.out

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c530a524-3c3d-4fcd-a45a-8b09f9fb16d1" />

I believe the issue is similar to #2735 premature signal handling

**Comment by killown** [comment]
Didn't test, just reading the code, if I am in the correct part of the issue:

xdg-toplevel.cpp:

```
    if (_current.fullscreen != _pending.fullscreen)
    {
        wait_for_client = true;
        this->target_configure = wlr_xdg_toplevel_set_fullscreen(toplevel, _pending.fullscreen);
    }
```

```
    if (wait_for_client)
    {
        // Send frame done to let the client know it update its state as fast as possible.
        main_surface->send_frame_done(true);
    } else
    {
        emit_ready();
    }
```

wait_for_client = true could never happen if the client doesn’t respond quickly or never, the compositor gets stuck in this state until next toggle

**Comment by killown** [comment]
@AgostinoA you can use this as a workaround until the fix is found:

```
from wayfire import WayfireSocket

sock = WayfireSocket()
sock.watch(["view-mapped"])

while True:
    msg = sock.read_next_event()
    view_id = msg["view"]["id"]
    fullscreen = msg["view"]["fullscreen"]
    if fullscreen:
        sock.set_view_fullscreen(view_id, False)
        sock.set_view_fullscreen(view_id, True)
```

**Comment by AgostinoA** [comment]
Do you have any suggestions for temporarily creating it as a plugin? I'm trying to get it working, but it doesn't seem to work.

```c++
#include <wayfire/plugin.hpp>
#include <wayfire/view.hpp>
#include <wayfire/toplevel-view.hpp>
#include <wayfire/core.hpp>
#include <wayfire/signal-definitions.hpp>
#include <wayfire/util.hpp>

class fullforce : public wf::plugin_interface_t
{       
    wf::signal::connection_t<wf::view_mapped_signal> on_view_mapped = [=](wf::view_mapped_signal *ev)
    {
        auto view = ev->view;
        if (!view || !view->is_mapped())
            return;
            
        // Only XWayland
        if (!view->get_app_id().empty())
            return;

        // Cast toplevel_view_interface_t
        auto toplevel = dynamic_cast<wf::toplevel_view_interface_t*>(view.get());
        if (!toplevel)
            return;
        
        if (toplevel->toplevel()->current().fullscreen)
        {
            LOGI("View mapped in fullscreen: ", view->get_title(), " force fullscreen");
            toplevel->toplevel()->pending().fullscreen = false;
            toplevel->toplevel()->commit();
            toplevel->toplevel()->pending().fullscreen = true;
            toplevel->toplevel()->commit();
            LOGI("Setted fullscreen: ", view->get_title());
        }
    };

public:
    void init() override
    {
    	LOGI("Full force wamos ");
        wf::get_core().connect(&on_view_mapped);
    }

    void fini() override
    {
        // Auto disconnect
    }
};

DECLARE_WAYFIRE_PLUGIN(fullforce);
```

**Comment by ammen99** [comment]
> Do you have any suggestions for temporarily creating it as a plugin? I'm trying to get it working, but it doesn't seem to work.
> 
> #include <wayfire/plugin.hpp>
> #include <wayfire/view.hpp>
> #include <wayfire/toplevel-view.hpp>
> #include <wayfire/core.hpp>
> #include <wayfire/signal-definitions.hpp>
> #include <wayfire/util.hpp>
> 
> class fullforce : public wf::plugin_interface_t
> {       
>     wf::signal::connection_t<wf::view_mapped_signal> on_view_mapped = [=](wf::view_mapped_signal *ev)
>     {
>         auto view = ev->view;
>         if (!view || !view->is_mapped())
>             return;
>             
>         // Only XWayland
>         if (!view->get_app_id().empty())
>             return;
> 
>         // Cast toplevel_view_interface_t
>         auto toplevel = dynamic_cast<wf::toplevel_view_interface_t*>(view.get());
>         if (!toplevel)
>             return;
>         
>         if (toplevel->toplevel()->current().fullscreen)
>         {
>             LOGI("View mapped in fullscreen: ", view->get_title(), " force fullscreen");
>             toplevel->toplevel()->pending().fullscreen = false;
>             toplevel->toplevel()->commit();
>             toplevel->toplevel()->pending().fullscreen = true;
>             toplevel->toplevel()->commit();
>             LOGI("Setted fullscreen: ", view->get_title());
>         }
>     };
> 
> public:
>     void init() override
>     {
>     	LOGI("Full force loaded ");
>         wf::get_core().connect(&on_view_mapped);
>     }
> 
>     void fini() override
>     {
>         // Auto disconnect
>     }
> };
> 
> DECLARE_WAYFIRE_PLUGIN(fullforce);

You need to call the fullscreen request functions (`wf::get_core().default_wm->fullscreen_request()`), setting the fullscreen state directly like you do won't change anythiing related to the size.

**Comment by ammen99** [comment]
Interestingly I cannot reproduce with the GLFW demo anymore, but the SDL demo from killown definitely reproduces the issue.
