### ISSUE TITLE
zxdg_exporter_v2#40: error 0: surface must be an xdg_toplevel The Wayland connection experienced a fatal error: Protocol error

### ISSUE THREAD

**Issue by er-bharat** [WayfireWM/wayfire#2701]
**Describe the bug**
some qt apps ( akregator, kmail ) crashes on selecting top menus with this in terminal
`zxdg_exporter_v2#40: error 0: surface must be an xdg_toplevel
The Wayland connection experienced a fatal error: Protocol error
`
this dont happen in hyprland, labwc so this must be wayfire bug

**To Reproduce**
1. open akregator
2. try to open settings window or any top menus
3. app instantly crashes

**Expected behavior**
clicking on top menus open popdown and dont crash.

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

**Wayfire version**
0.10.0-071f6e3f (Jul  1 2025) branch master wlroots-0.18.2

**Comment by killown** [comment]
This is definitely a Wayfire bug. Tested the apps in GNOME, Sway, Hyprland, and Weston, they all worked fine.

**Comment by ammen99** [comment]
@killown Ok, interesting. I think to make it simpler we can have the xdg toplevel controller class wait for the initial configure to create the view:

https://github.com/WayfireWM/wayfire/blob/2a5e8702f21a1538d4d4e6e2704238ea47ab621b/src/view/xdg-shell/xdg-toplevel-view.cpp#L560

Which is what wlroots used to do for us.

**Comment by ammen99** [comment]
here is an example implementation: https://0x0.st/80eT.diff

please try this out and let me know whether the bug is really fixed by this.

**Comment by killown** [comment]
Your patch didn't fix. I already tested these callbacks.

**Wayfire**:
```
[4116541.386] {Default Queue}  -> wl_compositor#5.create_surface(new id wl_surface#52)
[4116541.396] {Default Queue}  -> wp_fractional_scale_manager_v1#17.get_fractional_scale(new id wp_fractional_scale_v1#61, wl_surface#52)
[4116541.403] {Default Queue}  -> wp_viewporter#16.get_viewport(new id wp_viewport#57, wl_surface#52)
[4116541.688] {Default Queue}  -> wp_viewport#57.set_destination(318, 182)
[4116541.697] {Default Queue}  -> wl_compositor#5.create_region(new id wl_region#64)
[4116541.703] {Default Queue}  -> wl_region#64.add(0, 0, 318, 182)
[4116541.709] {Default Queue}  -> wl_surface#52.set_opaque_region(wl_region#64)
[4116541.714] {Default Queue}  -> wl_region#64.destroy()
[4116541.730] {Default Queue}  -> wl_surface#52.attach(nil, 0, 0)
[4116541.736] {Default Queue}  -> wl_surface#52.commit()
[4116541.744] {Default Queue}  -> xdg_wm_base#3.get_xdg_surface(new id xdg_surface#65, wl_surface#52)
[4116541.751] {Default Queue}  -> xdg_wm_base#3.create_positioner(new id xdg_positioner#66)
[4116541.758] {Default Queue}  -> xdg_positioner#66.set_anchor_rect(325, 19, 1, 1)
[4116541.763] {Default Queue}  -> xdg_positioner#66.set_anchor(5)
[4116541.767] {Default Queue}  -> xdg_positioner#66.set_gravity(8)
[4116541.771] {Default Queue}  -> xdg_positioner#66.set_size(318, 182)
[4116541.776] {Default Queue}  -> xdg_positioner#66.set_constraint_adjustment(3)
[4116541.781] {Default Queue}  -> xdg_surface#65.get_popup(new id xdg_popup#67, xdg_surface#49, xdg_positioner#66)
[4116541.786] {Default Queue}  -> xdg_positioner#66.destroy()
[4116541.791] {Default Queue}  -> xdg_popup#67.grab(wl_seat#10, 1413)
[4116541.801] {Default Queue}  -> wp_viewport#57.set_destination(318, 182)
[4116541.807] {Default Queue}  -> wp_viewport#57.set_destination(318, 182)
[4116541.813] {Default Queue}  -> wl_surface#52.set_buffer_transform(0)
[4116541.817] {Default Queue}  -> wl_surface#52.commit()
[4116541.821] {Default Queue}  -> wp_viewport#57.set_destination(318, 182)
[4116541.826] {Default Queue}  -> xdg_wm_base#3.create_positioner(new id xdg_positioner#68)
[4116541.832] {Default Queue}  -> xdg_positioner#68.set_anchor_rect(325, 19, 1, 1)
[4116541.836] {Default Queue}  -> xdg_positioner#68.set_anchor(5)
[4116541.842] {Default Queue}  -> xdg_positioner#68.set_gravity(8)
[4116541.846] {Default Queue}  -> xdg_positioner#68.set_size(318, 182)
[4116541.850] {Default Queue}  -> xdg_positioner#68.set_constraint_adjustment(3)
[4116541.855] {Default Queue}  -> xdg_popup#67.reposition(xdg_positioner#68, 1)
[4116541.859] {Default Queue}  -> xdg_positioner#68.destroy()
[4116542.065] {Display Queue} wl_display#1.delete_id(64)
[4116542.071] {Display Queue} wl_display#1.delete_id(66)
[4116542.074] {Display Queue} wl_display#1.delete_id(68)
[4116543.924]  -> wl_surface#41.frame(new id wl_callback#68)
[4116543.943] {mesa egl surface queue} wl_buffer#60.release()
[4116543.950] {mesa egl surface queue} wl_callback#63.done(1412)
[4116544.082] {mesa egl surface queue}  -> wl_surface#41.attach(wl_buffer#60, 0, 0)
[4116544.086] {mesa egl surface queue}  -> wl_surface#41.damage_buffer(0, 0, 2147483647, 2147483647)
[4116544.089] {mesa egl surface queue}  -> wl_surface#41.commit()
[4116544.094] {mesa egl surface queue}  -> wl_display#1.sync(new id wl_callback#63)
[4116544.110] {Default Queue} xdg_popup#67.repositioned(1)
[4116544.114] {Default Queue} xdg_popup#67.configure(325, 19, 318, 182)
[4116544.118] {Default Queue} xdg_surface#65.configure(1414)
[4116544.122] {Default Queue}  -> xdg_surface#65.ack_configure(1414)
[4116544.127] {Default Queue}  -> wp_viewport#57.set_destination(318, 182)
[4116544.132] {Default Queue}  -> xdg_surface#65.set_window_geometry(0, 0, 318, 182)
[4116544.167] {Default Queue}  -> wl_shm#4.create_pool(new id wl_shm_pool#66, fd 68, 231504)
[4116544.171] {Default Queue}  -> wl_shm_pool#66.create_buffer(new id wl_buffer#64, 0, 318, 182, 1272, 0)
[4116544.364] {Display Queue} wl_display#1.delete_id(63)
[4116544.373] {Display Queue} wl_display#1.delete_id(68)
[4116544.381] wl_callback#68.done(1102759)
[4116546.065]  -> wl_surface#52.frame(new id wl_callback#68)
[4116546.073] {Default Queue}  -> wl_surface#52.offset(0, 0)
[4116546.078] {Default Queue}  -> wl_surface#52.attach(wl_buffer#64, 0, 0)
[4116546.083] {Default Queue}  -> wl_surface#52.damage_buffer(0, 0, 318, 182)
[4116546.088] {Default Queue}  -> wl_surface#52.commit()
[4116546.477] {Default Queue} wl_keyboard#22.leave(1415, wl_surface#41)
[4116546.485] {Default Queue}  -> wl_display#1.sync(new id wl_callback#69)
[4116546.489] {Default Queue} wl_keyboard#22.enter(1416, wl_surface#52, array[0])
[4116546.496] {Default Queue} wl_keyboard#22.modifiers(1417, 0, 0, 16, 0)
[4116546.502] {Default Queue} wl_data_device#11.data_offer(new id wl_data_offer#4278190084)
[4116546.506] {Default Queue} wl_data_offer#4278190084.offer("text/plain")
[4116546.512] {Default Queue} wl_data_offer#4278190084.offer("text/plain;charset=utf-8")
[4116546.515] {Default Queue} wl_data_offer#4278190084.offer("TEXT")
[4116546.519] {Default Queue} wl_data_offer#4278190084.offer("STRING")
[4116546.524] {Default Queue} wl_data_offer#4278190084.offer("UTF8_STRING")
[4116546.528] {Default Queue} wl_data_device#11.selection(wl_data_offer#4278190084)
[4116546.532] {Default Queue}  -> wl_data_offer#4278190082.destroy()
[4116546.538] {Default Queue} zwp_primary_selection_device_v1#12.data_offer(new id zwp_primary_selection_offer_v1#4278190085)
[4116546.542] {Default Queue} zwp_primary_selection_offer_v1#4278190085.offer("text/plain;charset=utf-8")
[4116546.547] {Default Queue} zwp_primary_selection_offer_v1#4278190085.offer("UTF8_STRING")
[4116546.550] {Default Queue} zwp_primary_selection_offer_v1#4278190085.offer("COMPOUND_TEXT")
[4116546.554] {Default Queue} zwp_primary_selection_offer_v1#4278190085.offer("TEXT")
[4116546.558] {Default Queue} zwp_primary_selection_offer_v1#4278190085.offer("text/plain")
[4116546.562] {Default Queue} zwp_primary_selection_offer_v1#4278190085.offer("STRING")
[4116546.566] {Default Queue} zwp_primary_selection_device_v1#12.selection(zwp_primary_selection_offer_v1#4278190085)
[4116546.570] {Default Queue}  -> zwp_primary_selection_offer_v1#4278190083.destroy()
[4116546.574] {Default Queue} zwp_tablet_pad_v2#4278190081.leave(1418, wl_surface#41)
[4116546.578] {Default Queue} zwp_tablet_pad_v2#4278190081.enter(1419, zwp_tablet_v2#4278190080, wl_surface#52)
[4116546.583] {Default Queue} wl_buffer#64.release()
[4116546.586] {Default Queue} wl_surface#52.enter(wl_output#20)
[4116546.591] {Default Queue} wp_fractional_scale_v1#61.preferred_scale(120)
[4116546.595] {Default Queue}  -> wp_viewport#57.set_destination(318, 182)
[4116546.600] {Default Queue}  -> xdg_surface#65.set_window_geometry(0, 0, 318, 182)
[4116546.606] {Default Queue} wl_surface#52.preferred_buffer_scale(1)
[4116546.618] {Default Queue}  -> wl_surface#52.offset(0, 0)
[4116546.622] {Default Queue}  -> wl_surface#52.attach(wl_buffer#64, 0, 0)
[4116546.627] {Default Queue}  -> wl_surface#52.damage_buffer(0, 0, 318, 182)
[4116546.631] {Default Queue}  -> wl_surface#52.commit()
[4116546.655] {Display Queue} wl_display#1.delete_id(69)
[4116546.659] {Default Queue} wl_callback#69.done(1419)
[4116546.693] {Default Queue}  -> zxdg_exporter_v2#58.export_toplevel(new id zxdg_exported_v2#69, wl_surface#52)
[4116546.742] {Default Queue} wl_buffer#64.release()
[4116546.760] {Display Queue} wl_display#1.error(zxdg_exporter_v2#58, 0, "surface must be an xdg_toplevel")
zxdg_exporter_v2#58: error 0: surface must be an xdg_toplevel
```

**Sway**:

```
[ 173253.913] {Default Queue} xdg_toplevel#52.configure(768, 480, array[0])
[ 173253.918] {Default Queue} xdg_surface#51.configure(722)
[ 173253.958] {Default Queue}  -> xdg_surface#51.ack_configure(722)
[ 173253.967] {Default Queue}  -> wp_viewport#45.set_destination(768, 480)
[ 173253.971] {Default Queue}  -> xdg_surface#51.set_window_geometry(0, 0, 768, 480)
[ 173253.980] {Default Queue}  -> xdg_surface#51.set_window_geometry(0, 0, 768, 480)
[ 173254.514]  -> wl_surface#43.frame(new id wl_callback#71)
[ 173254.529] {mesa egl surface queue} wl_buffer#58.release()
[ 173254.536] {mesa egl surface queue} wl_callback#64.done(720)
[ 173254.639] {mesa egl surface queue}  -> wl_surface#43.attach(wl_buffer#58, 0, 0)
[ 173254.643] {mesa egl surface queue}  -> wl_surface#43.damage_buffer(0, 0, 2147483647, 2147483647)
[ 173254.646] {mesa egl surface queue}  -> wl_surface#43.commit()
[ 173254.648] {mesa egl surface queue}  -> wl_display#1.sync(new id wl_callback#64)
[ 173254.688] {Display Queue} wl_display#1.delete_id(69)
[ 173254.700] {Display Queue} wl_display#1.delete_id(64)
[ 173254.705] {Default Queue} wl_callback#69.done(727)
[ 173256.343] {mesa egl surface queue} wl_buffer#70.release()
[ 173256.351] {mesa egl surface queue} wl_callback#64.done(727)
[ 173267.070] {Display Queue} wl_display#1.delete_id(71)
[ 173267.081] wl_callback#71.done(1454449)
[ 173267.096]  -> wl_surface#43.frame(new id wl_callback#71)
[ 173267.111] {mesa egl surface queue}  -> wl_surface#43.attach(wl_buffer#70, 0, 0)
[ 173267.122] {mesa egl surface queue}  -> wl_surface#43.damage_buffer(0, 0, 2147483647, 2147483647)
[ 173267.125] {mesa egl surface queue}  -> wl_surface#43.commit()
[ 173267.127] {mesa egl surface queue}  -> wl_display#1.sync(new id wl_callback#64)
[ 173267.166] {Display Queue} wl_display#1.delete_id(64)
[ 173280.453] {Display Queue} wl_display#1.delete_id(71)
[ 173280.457] wl_callback#71.done(1454463)
[ 189398.275] {Default Queue} wl_keyboard#23.enter(733, wl_surface#43, array[0])
[ 189398.295] {Default Queue}  -> wl_display#1.sync(new id wl_callback#71)
[ 189398.299] {Default Queue} wl_keyboard#23.modifiers(734, 0, 0, 16, 0)
[ 189398.303] {Default Queue} wl_data_device#16.selection(nil)
[ 189398.307] {Default Queue} zwp_primary_selection_device_v1#20.selection(nil)
[ 189398.310] {Default Queue} wl_pointer#24.enter(736, wl_surface#43, 765.90234375, 444.31640625)
[ 189398.315] {Default Queue}  -> wp_cursor_shape_device_v1#25.set_shape(736, 1)
[ 189398.318] {Default Queue} wl_pointer#24.frame()
[ 189398.327] {Default Queue} wl_pointer#24.motion(1470580, 765.89843750, 444.31640625)
[ 189398.331] {Default Queue} wl_pointer#24.frame()
[ 189398.334] {Default Queue} xdg_toplevel#52.configure(768, 480, array[4])
[ 189398.338] {Default Queue} xdg_surface#51.configure(732)
[ 189398.396] {Default Queue}  -> xdg_surface#51.ack_configure(732)
[ 189398.403] {Default Queue}  -> wp_viewport#45.set_destination(768, 480)
[ 189398.406] {Default Queue}  -> xdg_surface#51.set_window_geometry(0, 0, 768, 480)
[ 189398.413] {Default Queue}  -> xdg_surface#51.set_window_geometry(0, 0, 768, 480)
[ 189398.470]  -> wl_surface#43.frame(new id wl_callback#69)
[ 189398.493] {mesa egl surface queue} wl_buffer#58.release()
[ 189398.497] {mesa egl surface queue} wl_callback#64.done(727)
[ 189398.582] {Display Queue} wl_display#1.delete_id(71)
[ 189398.620] {mesa egl surface queue}  -> wl_surface#43.attach(wl_buffer#58, 0, 0)
[ 189398.628] {mesa egl surface queue}  -> wl_surface#43.damage_buffer(0, 0, 2147483647, 2147483647)
[ 189398.649] {mesa egl surface queue}  -> wl_surface#43.commit()
[ 189398.653] {mesa egl surface queue}  -> wl_display#1.sync(new id wl_callback#64)
[ 189398.667] {Default Queue} wl_callback#71.done(736)
[ 189398.708] {Display Queue} wl_display#1.delete_id(64)
[ 189400.591] {mesa egl surface queue} wl_buffer#70.release()
[ 189400.600] {mesa egl surface queue} wl_callback#64.done(736)
[ 189404.010] {Display Queue} wl_display#1.delete_id(69)
[ 189404.018] wl_callback#69.done(1470586)
[ 189404.031]  -> wl_surface#43.frame(new id wl_callback#69)
[ 189404.043] {mesa egl surface queue}  -> wl_surface#43.attach(wl_buffer#70, 0, 0)
[ 189404.047] {mesa egl surface queue}  -> wl_surface#43.damage_buffer(0, 0, 2147483647, 2147483647)
[ 189404.050] {mesa egl surface queue}  -> wl_surface#43.commit()
[ 189404.053] {mesa egl surface queue}  -> wl_display#1.sync(new id wl_callback#64)


```
