### ISSUE TITLE
Dialog placement with multilple workspaces

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#582]
Hi,

this is a behavior I noticed while experimenting with the scale plugin and I find it strange. It seems that modal dialogs have a placement that is the same on all workspaces and are hidden / shown according to whether their parent is visible.

Normal windows / views can be placed to span multiple workspaces and they display consistently in the overview. On the other hand, child dialogs have a strange behavior that they are placed at the same position on each workspace the parent is visible on.

Steps to reproduce:
1. Place a window that it spans multiple workspaces (e.g. nautilus in the first screenshot)
2. Open a modal dialog (e.g. properties) and place it that it also spans more than one workspace (see second screenshot)
3. Switch to the other workspace that the views should occupy (the one to the right in this case)
4. Parent view is in expected location, the dialog is however in the same absolute location as in the other workspace (note: third screenshot is in the top middle workspace, 4th screenshot is in the top right one)

Expected behavior:
Modal dialog is displayed as if it spans multiple workspaces, similar to its parent. E.g. in the fourth screenshot, I expect it to be in the left side of the workspace, showing its right half, instead of being in the right side of the workspace, showing its left half

Placement of main window:
![wayfire_dialog1](https://user-images.githubusercontent.com/6224679/87002244-c1bbb100-c1eb-11ea-9abb-b6a9099830ef.png)

Placement with dialog:
![wayfire_dialog2](https://user-images.githubusercontent.com/6224679/87002279-d7c97180-c1eb-11ea-841a-fc4052c0e47a.png)

Top middle workspace:
![wayfire_dialog3](https://user-images.githubusercontent.com/6224679/87002294-def07f80-c1eb-11ea-9e44-c0bd86f44be1.png)

Top right workspace, dialog is in the "wrong" location:
![wayfire_dialog4](https://user-images.githubusercontent.com/6224679/87002320-eadc4180-c1eb-11ea-825c-7159ab1dadd3.png)

**Comment by soreau** [comment]
Another thing I noticed related to this is when switching workspaces with a view that has a dialog associated, i.e. vswitch-with-view binding, the parent view animates while the child just appears after the animation completes. Even when simply switching to a workspace that has a view with an open dialog, the child is not rendered during the switch animation but appears after the workspace switch animation completes.

**Comment by dkondor** [comment]
Hi,

I've just tested this again. Now my original problem is fixed (parent and child spanning two workspaces), but I'm seeing another issue.
If I move the parent to a different workspace (in the expo view) without moving the child, the child "disappears". It stays on the original workspace, but becomes invisible. Moving the mouse over it, I can notice it is still there (mouse cursor changes at the edges and if there's e.g. a text entry).

Steps to reproduce:
1. Open a view with a child (e.g. nautilus with properties) on any workspace
2. Start expo
3. Drag the parent view to a different workspace

The result is that the child (dialog) disappears. It reappears later if the parent is dragged back to the same workspace.

**Comment by ammen99** [comment]
> Steps to reproduce:
> 
> 1. Open a view with a child (e.g. nautilus with properties) on any workspace
> 2. Start expo
> 3. Drag the parent view to a different workspace
> 
> The result is that the child (dialog) disappears. It reappears later if the parent is dragged back to the same workspace.

I suppose you just want to use https://github.com/WayfireWM/wayfire-plugins-extra/blob/master/src/join-views.cpp :) 

Though I suppose without it the behavior still isn't perfect. I suppose we should always ensure that the child view remains visible on the workspace the main view is on.

**Comment by ammen99** [comment]
Or should we just make sure the child view is visible on the original workspace?

**Comment by dkondor** [comment]
I'm unsure what would be the best behavior. The child following the parent can lead to some edge cases, like my original problem here. "Hiding" the child is in any case confusing.

As a user, there is one thing that can be very annoying (this happens e.g. when using compiz):
1. Open a window on workspace A
2. Switch to workspace B
3. Some event triggers a child for the original window to appear (e.g. Firefox asking for master password)
4. Child window appears on workspace B
5. Now, if I switch back to workspace A, the original window is unresponsive, without any indication that it has a child on some other workspace. I have to search where it might be (or use scale or similar overview).

As far as I understand, this problem is already avoided on wayfire by placing new child views on the same workspace as the parent (I was trying to test this with the latest scale+master branch and it seems OK). The question is only what should happen if the user deliberately moves the parent / child, which might be a preference, handled by the join-views plugin as you suggest.
