### ISSUE TITLE
GIMP dialog windows misbehavior on multi-headed setup

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#768]
This may be difficult to describe, but let's try. I work on a laptop with 2 external displays:

```text
[DP-1]
layout = 0,0
mode = 1920x1080@60.000000
scale = 1.000000
transform = normal

[eDP-1]
layout = 1920,0
mode = 1920x1080@120.000000
scale = 1.000000
transform = normal

[HDMI-A-1]
layout = 3840,0
mode = 1920x1080@60.000000
scale = 1.000000
transform = normal
```

If I open GIMP on `DP-1`, it works correctly on all workspaces. The problem appears on `eDP-1` and `HDMI-A-1`. I use the default 3x3 workspaces matrix. If I open GIMP on one of workspaces in the left column (1, 4 or 7), dialog popups are being moved to the left margin. On all other workspaces, they land somewhere off the screen. I use Waybar with the `wlr/taskbar` module. If I click on the button corresponding to the missing window, I'm being moved to the first left workspace in the same row. 

Sample steps to reproduce:

- launch GIMP on a display which coordinates are not 0,0 and workspace 2, 3, 5, 6, 8 or 9;
- open an image
- select Image / Canvas size
- change width or height, press Center

The dialog popup disappears from the screen.

**Comment by ammen99** [comment]
Hi, I also noticed similar, a recent PR broke stuff. I have a fix in #767, can you try that?

**Comment by nwg-piotr** [comment]
As soon as I'm back home. Just started Friday At The Office, and I only have my old lappy, with no external display. :D

**Comment by nwg-piotr** [comment]
I stole a spare monitor from another desk, but for some reason I'm unable to build:

```
$ ninja -C build
ninja: Entering directory `build'
[132/223] Compiling C++ object src/wayfire.p/view_xwayland.cpp.o
FAILED: src/wayfire.p/view_xwayland.cpp.o
c++ -Isrc/wayfire.p -Isrc -I../src -I. -I.. -I../src/api -Isubprojects/wf-config/include -I../subprojects/wf-config/include -Isubprojects/wf-utils -I../subprojects/wf-utils -Isubprojects/wf-touch -I../subprojects/wf-touch -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -g '-DWAYFIRE_VERSION="0.5.0-4d3d6c3 (" __DATE__ ", branch '"'"'HEAD'"'"')"' -DWLR_USE_UNSTABLE -Wno-unused-parameter -DHAS_ADDR2LINE=1 -MD -MQ src/wayfire.p/view_xwayland.cpp.o -MF src/wayfire.p/view_xwayland.cpp.o.d -o src/wayfire.p/view_xwayland.cpp.o -c ../src/view/xwayland.cpp
../src/view/xwayland.cpp: In lambda function:
../src/view/xwayland.cpp:364:24: error: ‘wlr_xwayland_minimize_event’ was not declared in this scope; did you mean ‘wlr_xwayland_resize_event’?
  364 |             auto ev = (wlr_xwayland_minimize_event*)data;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        wlr_xwayland_resize_event
../src/view/xwayland.cpp:364:52: error: expected primary-expression before ‘)’ token
  364 |             auto ev = (wlr_xwayland_minimize_event*)data;
      |                                                    ^
../src/view/xwayland.cpp: In member function ‘virtual void wayfire_xwayland_view::initialize()’:
../src/view/xwayland.cpp:406:49: error: ‘struct wlr_xwayland_surface::<unnamed>’ has no member named ‘request_minimize’; did you mean ‘request_maximize’?
  406 |         on_request_minimize.connect(&xw->events.request_minimize);
      |                                                 ^~~~~~~~~~~~~~~~
      |                                                 request_maximize
../src/view/xwayland.cpp: In member function ‘virtual void wayfire_xwayland_view::set_minimized(bool)’:
../src/view/xwayland.cpp:615:13: error: ‘wlr_xwayland_surface_set_minimized’ was not declared in this scope; did you mean ‘wlr_xwayland_surface_set_maximized’?
  615 |             wlr_xwayland_surface_set_minimized(xw, minimized);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             wlr_xwayland_surface_set_maximized
[137/223] Compiling C++ object src/wayfire.p/output_plugin-loader.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by ammen99** [comment]
You have not updated your wlroots library, you need latest master to build wayfire master.

**Comment by nwg-piotr** [comment]
Allright, it builds well now. However, #767 does not resolve the issue. The only changes I noticed is that the dialog window opened on any other workspace than 1, 4 and 7 **on any display** appears nowhere from the very beginning.

**Comment by ammen99** [comment]
Hmm, that's bad, I'll have to work more on that then (however I won't be able to do that this weekend). As a workaround, I believe if you go back to commit c657fa1ac30051099d483764df25d2fc573b4e6b it should work.

**Comment by nwg-piotr** [comment]
No hurry, without #767 I can use GIMP where it works well. BTW: after applying the patch, also dialogs in my Azote started behaving the same way, while previously they appeared where they should.

For now I'll just stick to 0.5.0, and switch to master when my most awaited https://github.com/WayfireWM/wayfire-plugins-extra/pull/44 is merged.

**Comment by ammen99** [comment]
@nwg-piotr Could you try #767 again? (I had made a mistake which should now be fixed)

**Comment by nwg-piotr** [comment]
This does not damage the behavior of other GTK apps, as the previous version did, but the GIMP issue persists:

- on a display of `Position: 0,0` dialogs in all GTK apps behave perfectly well on all workspaces, and so do dialogs in GIMP.
- on a display of `Position: 1920,0` all dialogs in GTK apps behave properly - except for GIMP. Description and steps to reproduce same as in OP.

**Comment by ammen99** [comment]
Thanks for the test. So this is indeed a gimp-specific bug, soreau has also been able to reproduce it.

**Comment by nwg-piotr** [comment]
Yep, since all other apps behave well, I could live with it.

**Comment by soreau** [comment]
There are gtk2 and gtk3 apps. The former needs xwayland while the latter has an option. It should be made clear if these apps are using xwayland or not.

**Comment by ammen99** [comment]
> There are gtk2 and gtk3 apps. The former needs xwayland while the latter has an option. It should be made clear if these apps are using xwayland or not.

GIMP is currently a GTK2 app and uses Xwayland.

**Comment by soreau** [comment]
And the others referenced?

**Comment by ammen99** [comment]
> And the others referenced?

The other apps are mentioned as working so I don't see how they're relevant? I'd assume they are wayland-native apps.

**Comment by ammen99** [comment]
Plus even if they were Xwayland applications there are a ton of different behaviors of Xwayland applications so it can't really tell us much.

**Comment by soreau** [comment]
What I am getting at is that xwayland might position gimp one way and other apps another way (esp. since apps can be in control of their position) so that it is really an xwayland-under-wayfire client bug than a gimp one. It doesn't make sense to blame gimp when it works just fine in real X.

**Comment by ammen99** [comment]
When did I say this is GIMP's bug? I said this is a bug which happens only with GIMP so far.

**Comment by soreau** [comment]
> Thanks for the test. So this is indeed a gimp-specific bug, soreau has also been able to reproduce it.

gimp-specific sounds like 'a bug in gimp'.

**Comment by soreau** [comment]
Rather, it's xwayland-on-wayfire specific.

**Comment by nwg-piotr** [comment]
For clarification: as well Caja (xwayland) as Thunar (wayland) both behave well.

**Comment by soreau** [comment]
As @ammen99 found on IRC, if you revert a910ef39f, gimp should work correctly.

**Comment by nwg-piotr** [comment]
Can't build it. Wrong `wlroots` version?

```
$ ninja -C build
ninja: Entering directory `build'
[30/62] Compiling C++ object src/wayfire.p/view_xwayland.cpp.o
FAILED: src/wayfire.p/view_xwayland.cpp.o
c++ -Isrc/wayfire.p -Isrc -I../src -I. -I.. -I../src/api -Isubprojects/wf-config/include -I../subprojects/wf-config/include -Isubprojects/wf-utils -I../subprojects/wf-utils -Isubprojects/wf-touch -I../subprojects/wf-touch -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -g '-DWAYFIRE_VERSION="0.5.0-f56a9b0 (" __DATE__ ", branch '"'"'HEAD'"'"')"' -DWLR_USE_UNSTABLE -Wno-unused-parameter -DHAS_ADDR2LINE=1 -MD -MQ src/wayfire.p/view_xwayland.cpp.o -MF src/wayfire.p/view_xwayland.cpp.o.d -o src/wayfire.p/view_xwayland.cpp.o -c ../src/view/xwayland.cpp
../src/view/xwayland.cpp: In lambda function:
../src/view/xwayland.cpp:358:24: error: ‘wlr_xwayland_minimize_event’ was not declared in this scope; did you mean ‘wlr_xwayland_resize_event’?
  358 |             auto ev = (wlr_xwayland_minimize_event*)data;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        wlr_xwayland_resize_event
../src/view/xwayland.cpp:358:52: error: expected primary-expression before ‘)’ token
  358 |             auto ev = (wlr_xwayland_minimize_event*)data;
      |                                                    ^
../src/view/xwayland.cpp: In member function ‘virtual void wayfire_xwayland_view::initialize()’:
../src/view/xwayland.cpp:400:49: error: ‘struct wlr_xwayland_surface::<unnamed>’ has no member named ‘request_minimize’; did you mean ‘request_maximize’?
  400 |         on_request_minimize.connect(&xw->events.request_minimize);
      |                                                 ^~~~~~~~~~~~~~~~
      |                                                 request_maximize
../src/view/xwayland.cpp: In member function ‘virtual void wayfire_xwayland_view::set_minimized(bool)’:
../src/view/xwayland.cpp:609:13: error: ‘wlr_xwayland_surface_set_minimized’ was not declared in this scope; did you mean ‘wlr_xwayland_surface_set_maximized’?
  609 |             wlr_xwayland_surface_set_minimized(xw, minimized);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             wlr_xwayland_surface_set_maximized
[39/62] Compiling C++ object plugins/decor/libdecoration.so.p/deco-layout.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by soreau** [comment]
To revert, you'd use `git revert a910ef3`.

**Comment by nwg-piotr** [comment]
Excellent. I've already got another issue to submit :rofl:

**Comment by soreau** [comment]
Does [this patch](http://ix.io/2Ah9) help?

**Comment by nwg-piotr** [comment]
On the display of Position: 0,0 all right on all workspaces. On other displays it's not perfect, but acceptable. See https://youtu.be/koAOb2wX5D0

**Comment by ammen99** [comment]
@nwg-piotr Can you post the output of `xwininfo -root -tree` when you experience this bug?

**Comment by nwg-piotr** [comment]
```text
$ xwininfo -root -tree

xwininfo: Window id: 0x527 (the root window) (has no name)

  Root window id: 0x527 (the root window) (has no name)
  Parent window id: 0x0 (none)
     16 children:
     0x400f48 "Ustawienie wymiarów płótna obrazu": ("gimp-2.10" "Gimp-2.10")  522x595+1920+243  +1920+243
        1 child:
        0x400f49 (has no name): ()  1x1+-1+-1  +1919+242
     0x400f4f "Edytor obrazów GIMP": ()  10x10+-100+-100  +-100+-100
     0x400eb7 "Edytor obrazów GIMP": ("gimp-2.10" "Gimp-2.10")  333x649+2158+53  +2158+53
        1 child:
        0x400eb8 (has no name): ()  1x1+-1+-1  +2157+52
     0x4006fb "Edytor obrazów GIMP": ("gimp-2.10" "Gimp-2.10")  389x334+2273+188  +2273+188
        1 child:
        0x4006fc (has no name): ()  1x1+-1+-1  +2272+187
     0x40064b "Edytor obrazów GIMP": ("gimp-2.10" "Gimp-2.10")  355x636+1920+53  +1920+53
        1 child:
        0x40064c (has no name): ()  1x1+-1+-1  +1919+52
     0x40009b "[frozen-frog] (zaimportowany)-1.0 (Kolory RGB 8-bitowa (gamma, stałoprzecinkowa), GIMP built-in sRGB, 1 warstwa) 1920x1080 – GIMP": ("gimp-2.10" "Gimp-2.10")  1920x1030+1920+26  +1920+26
        2 children:
        0x4000d4 (has no name): ()  182x136+0+57  +1920+83
        0x40009c (has no name): ()  1x1+-1+-1  +1919+25
     0x60001f "Chromium clipboard": ()  10x10+-100+-100  +-100+-100
     0x600007 "GIMP dialog windows misbehavior on multi-headed setup · Issue #768 · WayfireWM/wayfire – Chromium": ("chromium" "Chromium")  1920x1054+0+26  +0+26
        1 child:
        0xa00010 (has no name): ()  1920x1054+0+0  +0+26
     0x60000a (has no name): ()  1x1+0+0  +0+0
     0x800003 "chromium": ("chromium" "Chromium")  200x200+0+0  +0+0
        1 child:
        0x800004 (has no name): ()  1x1+-1+-1  +-1+-1
     0x800001 "chromium": ("chromium" "Chromium")  10x10+10+10  +10+10
     0x400021 (has no name): ()  1x1+-1+-1  +-1+-1
     0x400001 "Edytor obrazów GIMP": ("gimp-2.10" "Gimp-2.10")  10x10+10+10  +10+10
        1 child:
        0x400002 (has no name): ()  1x1+-1+-1  +9+9
     0x200003 "wlroots wm": ()  10x10+0+0  +0+0
     0x200002 (has no name): ()  8192x8192+0+0  +0+0
     0x200001 (has no name): ()  10x10+0+0  +0+0
```

**Comment by ammen99** [comment]
@nwg-piotr To me this looks like GIMP simply tries to position its dialogue on a different output. Looking at `xwininfo`, GIMP is positioned correctly by Wayfire, so we can't do much more, or can we @soreau?

**Comment by nwg-piotr** [comment]
Together with the patch from @soreau it's usable, even if sometimes behaves funny.

**Comment by ammen99** [comment]
> Together with the patch from @soreau it's usable, even if sometimes behaves funny.

Yes, the funny behavior is because gimp is for some reason trying to move the dialog to the left output (and wayfire does not allow this because the main window is on the middle output).

**Comment by nwg-piotr** [comment]
Most of what I use and 100% of what I code is GTK3-based and behaves well. GIMP has its oddities. I'd leave it as it with the patch applied.

**Comment by soreau** [comment]
> @nwg-piotr To me this looks like GIMP simply tries to position its dialogue on a different output. Looking at `xwininfo`, GIMP is positioned correctly by Wayfire, so we can't do much more, or can we @soreau?

@ammen99 Yes there is something we can do actually, and I've pushed the new code to the PR. I was able to reproduce the problem and it was because we were blindly subtracting the output layout position from the configure request position, but actually we should only do this if the requested geometry is in fact already greater than the layout dimension.

@nwg-piotr Can you retest the latest changes to the PR?

**Comment by nwg-piotr** [comment]
If fixes the issue. It also seems to have fixed unpredictable popups in PyCharm.

**Comment by soreau** [comment]
@nwg-piotr Can you retest the latest changes in that branch and make sure all your tests work?

**Comment by nwg-piotr** [comment]
> Can you retest the latest changes in that branch and make sure all your tests work?

Sorry, it was 4 or 5 am in my place. Works well.

**Comment by soreau** [comment]
@nwg-piotr FWIW, the canvas resize window was still moving when resizing or moving it. 1d23d0f9 was just pushed to master so the problem hopefully should be fixed once and for all.

**Comment by nwg-piotr** [comment]
One way or another, having installed from the current master and applied the [patch](http://ix.io/2AfK), I have no more thing to complain about.
